# Generated by Django 2.0.2 on 2018-03-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180307_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.PositiveIntegerField()),
                ('all', models.PositiveIntegerField()),
            ],
        ),
    ]
