# Generated by Django 2.0.2 on 2018-03-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_shots'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shots',
        ),
        migrations.AddField(
            model_name='brand',
            name='SeeFirst',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='SeeFirst',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='SeeFirst',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
