# Generated by Django 2.0.2 on 2018-03-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180307_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='SeeFirst',
            new_name='see_first',
        ),
    ]
