# Generated by Django 2.0.2 on 2018-03-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180307_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='SeeFirst',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='SeeFirst',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='see_first',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
