# Generated by Django 2.0.2 on 2018-03-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180307_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='SeeFirst',
        ),
        migrations.RemoveField(
            model_name='category',
            name='SeeFirst',
        ),
    ]
