# Generated by Django 2.0.2 on 2018-03-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
    ]
