# Generated by Django 2.0.2 on 2018-03-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180316_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='see_first',
        ),
    ]
